[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 4
fs_permissions = [{access='read', path='.'}]
remappings = ['ds-test/=lib/ds-test/src/']

[fmt] # See https://book.getfoundry.sh/reference/config/formatter
int_types = "short"
line_length = 120
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "single"
ignore = ['./script/**/*']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config